<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CanReplayPlayer.Scenarios</RootNamespace>
    <AssemblyName>CanReplayPlayer.Scenarios</AssemblyName>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CanReplayPlayer.Core\CanReplayPlayer.Core.csproj" />
  </ItemGroup>
</Project>
